name: Build and Publish ESPHome firmware and website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-word-clock-x:
    name: Publish Word Clock X
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: word-clock-x.yaml
      name: Word Clock X
      manifest_filename: word-clock-x-manifest.json
      clean: false
      esphome_version: latest